{% set name = "libdc1394" %}
{% set version = "2.2.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://downloads.sourceforge.net/project/libdc1394/libdc1394-2/{{ version }}/libdc1394-{{ version }}.tar.gz
    sha256: 537ceb78dd3cef271a183f4a176191d1cecf85f025520e6bd3758b0e19e6609f
    patches:
      - capture.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make

  host:
    - libusb

  run:
    - libusb

test:
  commands:
    - test -f $PREFIX/lib/libdc1394.dylib  # [osx]
    - test -f $PREFIX/lib/libdc1394.so  # [linux]

about:
  home: https://damien.douxchamps.net/ieee1394/libdc1394/
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Provides API for IEEE 1394 cameras.
  description: Provides API for IEEE 1394 cameras.

extra:
  recipe-maintainers:
    - traversaro
